task: davis
contrastive_split: within

drug_featurizer: MorganFeaturizer
target_featurizer: ProtBertFeaturizer
latent_dimension: 1024
prot_proj: "avg"
loss_type: "CE"
dropout: 0.0
sigmoid_scalar: 1

batch_size: 32
contrastive_batch_size: 256
shuffle: True
num_workers: 0

epochs: 50
every_n_val: 1
lr: 1e-4
lr_t0: 10
contrastive: True
contrastive_type: "default"
clr: 1e-5
clr_t0: 10
margin_fn: 'tanh_decay'
margin_max: 0.25
margin_t0: 10

replicate: 0

wandb_proj: ConPlexTrain
model_save_dir: ./best_models

