task: unittest
contrastive: False
InfoNCEWeight: 0.0

drug_featurizer: MorganFeaturizer
target_featurizer: ProtBertFeaturizer
latent_dimension: 1024
model_size: "small"
prot_proj: "agg"
loss_type: "CE"
dropout: 0
sigmoid_scalar: 5

batch_size: 32
shuffle: True
num_workers: 0

epochs: 50
every_n_val: 1
lr: 1e-4
lr_t0: 10
weight_decay: 0

replicate: 0

wandb_proj: ConPlexTrain
model_save_dir: ./best_models

